/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_rot_mpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

static const casadi_real casadi_c0[3] = {7.1428571428571435e+04, 7.1428571428571435e+04, 4.6082949308755764e+04};
static const casadi_real casadi_c1[3] = {1.4000000000000000e-05, 1.4000000000000000e-05, 2.1699999999999999e-05};

/* quad_rot_mpc_expl_ode_fun:(i0[7],i1[3],i2[4])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, w01, w02, *w03=w+10, w04, w05, w06, w07, w08, w09, *w10=w+23;
  casadi_real *w11=w+27, *w12=w+31, *w13=w+35, *w14=w+39, *w15=w+55, *w16=w+71, *w17=w+74, *w18=w+77, *w19=w+80;
  const casadi_real *cs, *ct;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w00, 4);
  /* #1: @1 = 0.5 */
  w01 = 5.0000000000000000e-01;
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = input[0][0] */
  casadi_copy(arg[0], 7, w03);
  /* #4: @4 = @3[4] */
  for (rr=(&w04), cs=w03+4; cs!=w03+5; cs+=1) *rr++ = *cs;
  /* #5: @5 = (-@4) */
  w05 = (- w04 );
  /* #6: @6 = @3[5] */
  for (rr=(&w06), cs=w03+5; cs!=w03+6; cs+=1) *rr++ = *cs;
  /* #7: @7 = (-@6) */
  w07 = (- w06 );
  /* #8: @8 = @3[6] */
  for (rr=(&w08), cs=w03+6; cs!=w03+7; cs+=1) *rr++ = *cs;
  /* #9: @9 = (-@8) */
  w09 = (- w08 );
  /* #10: @10 = horzcat(@2, @5, @7, @9) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  /* #11: @10 = @10' */
  /* #12: @11 = horzcat(@4, @2, @8, @7) */
  rr=w11;
  *rr++ = w04;
  *rr++ = w02;
  *rr++ = w08;
  *rr++ = w07;
  /* #13: @11 = @11' */
  /* #14: @12 = horzcat(@6, @9, @2, @4) */
  rr=w12;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w02;
  *rr++ = w04;
  /* #15: @12 = @12' */
  /* #16: @13 = horzcat(@8, @6, @5, @2) */
  rr=w13;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w02;
  /* #17: @13 = @13' */
  /* #18: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #19: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #20: @15 = (@1*@15) */
  for (i=0, rr=w15, cs=w15; i<16; ++i) (*rr++)  = (w01*(*cs++));
  /* #21: @10 = @3[:4] */
  for (rr=w10, cs=w03+0; cs!=w03+4; cs+=1) *rr++ = *cs;
  /* #22: @0 = mac(@15,@10,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w15+j, ct=w10+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #23: output[0][0] = @0 */
  casadi_copy(w00, 4, res[0]);
  /* #24: @16 = 
  [[71428.6, 00, 00], 
   [00, 71428.6, 00], 
   [00, 00, 46082.9]] */
  casadi_copy(casadi_c0, 3, w16);
  /* #25: @16 = nonzeros(@16) */
  /* #26: @17 = input[1][0] */
  casadi_copy(arg[1], 3, w17);
  /* #27: @18 = 
  [[1.4e-05, 00, 00], 
   [00, 1.4e-05, 00], 
   [00, 00, 2.17e-05]] */
  casadi_copy(casadi_c1, 3, w18);
  /* #28: @18 = nonzeros(@18) */
  /* #29: @19 = @3[4:7] */
  for (rr=w19, cs=w03+4; cs!=w03+7; cs+=1) *rr++ = *cs;
  /* #30: @18 = (@18*@19) */
  for (i=0, rr=w18, cs=w19; i<3; ++i) (*rr++) *= (*cs++);
  /* #31: @1 = @18[2] */
  for (rr=(&w01), cs=w18+2; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #32: @5 = (@6*@1) */
  w05  = (w06*w01);
  /* #33: @2 = @18[1] */
  for (rr=(&w02), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #34: @9 = (@8*@2) */
  w09  = (w08*w02);
  /* #35: @5 = (@5-@9) */
  w05 -= w09;
  /* #36: @9 = @18[0] */
  for (rr=(&w09), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #37: @8 = (@8*@9) */
  w08 *= w09;
  /* #38: @1 = (@4*@1) */
  w01  = (w04*w01);
  /* #39: @8 = (@8-@1) */
  w08 -= w01;
  /* #40: @4 = (@4*@2) */
  w04 *= w02;
  /* #41: @6 = (@6*@9) */
  w06 *= w09;
  /* #42: @4 = (@4-@6) */
  w04 -= w06;
  /* #43: @18 = vertcat(@5, @8, @4) */
  rr=w18;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w04;
  /* #44: @17 = (@17-@18) */
  for (i=0, rr=w17, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #45: @16 = (@16*@17) */
  for (i=0, rr=w16, cs=w17; i<3; ++i) (*rr++) *= (*cs++);
  /* #46: output[0][1] = @16 */
  if (res[0]) casadi_copy(w16, 3, res[0]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_rot_mpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 83;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 83*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
