/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_rot_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {10, 1, 1};

static const casadi_real casadi_c0[3] = {1.4000000000000000e-05, 1.4000000000000000e-05, 2.1699999999999999e-05};
static const casadi_real casadi_c1[3] = {7.1428571428571435e+04, 7.1428571428571435e+04, 4.6082949308755764e+04};

/* quad_rot_mpc_expl_vde_adj:(i0[7],i1[7],i2[3],i3[4])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, *w01=w+11, *w02=w+14, *w03=w+21, w04, *w05=w+25, *w06=w+28, *w07=w+35, *w08=w+39, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+51, *w19=w+55, *w20=w+59, *w21=w+63, *w22=w+67;
  casadi_real *w23=w+71, *w24=w+87;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w00, 7);
  /* #1: @1 = 
  [[1.4e-05, 00, 00], 
   [00, 1.4e-05, 00], 
   [00, 00, 2.17e-05]] */
  casadi_copy(casadi_c0, 3, w01);
  /* #2: @1 = nonzeros(@1) */
  /* #3: @2 = input[0][0] */
  casadi_copy(arg[0], 7, w02);
  /* #4: @3 = @2[4:7] */
  for (rr=w03, cs=w02+4; cs!=w02+7; cs+=1) *rr++ = *cs;
  /* #5: @3 = (@1*@3) */
  for (i=0, rr=w03, cr=w01, cs=w03; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #6: @4 = @3[1] */
  for (rr=(&w04), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #7: @5 = 
  [[71428.6, 00, 00], 
   [00, 71428.6, 00], 
   [00, 00, 46082.9]] */
  casadi_copy(casadi_c1, 3, w05);
  /* #8: @5 = nonzeros(@5) */
  /* #9: @6 = input[1][0] */
  casadi_copy(arg[1], 7, w06);
  /* #10: {@7, @8} = vertsplit(@6) */
  casadi_copy(w06, 4, w07);
  casadi_copy(w06+4, 3, w08);
  /* #11: @5 = (@5*@8) */
  for (i=0, rr=w05, cs=w08; i<3; ++i) (*rr++) *= (*cs++);
  /* #12: @8 = (-@5) */
  for (i=0, rr=w08, cs=w05; i<3; ++i) *rr++ = (- *cs++ );
  /* #13: {@9, @10, @11} = vertsplit(@8) */
  w09 = w08[0];
  w10 = w08[1];
  w11 = w08[2];
  /* #14: @12 = (@4*@11) */
  w12  = (w04*w11);
  /* #15: @13 = @3[2] */
  for (rr=(&w13), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #16: @14 = (@13*@10) */
  w14  = (w13*w10);
  /* #17: @12 = (@12-@14) */
  w12 -= w14;
  /* #18: (@0[4] += @12) */
  for (rr=w00+4, cs=(&w12); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #19: @12 = @3[0] */
  for (rr=(&w12), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #20: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #21: @4 = (@4*@9) */
  w04 *= w09;
  /* #22: @14 = (@14-@4) */
  w14 -= w04;
  /* #23: (@0[6] += @14) */
  for (rr=w00+6, cs=(&w14); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #24: @3 = zeros(3x1) */
  casadi_clear(w03, 3);
  /* #25: @14 = @2[6] */
  for (rr=(&w14), cs=w02+6; cs!=w02+7; cs+=1) *rr++ = *cs;
  /* #26: @4 = (@14*@10) */
  w04  = (w14*w10);
  /* #27: @15 = @2[5] */
  for (rr=(&w15), cs=w02+5; cs!=w02+6; cs+=1) *rr++ = *cs;
  /* #28: @16 = (@15*@11) */
  w16  = (w15*w11);
  /* #29: @4 = (@4-@16) */
  w04 -= w16;
  /* #30: (@3[0] += @4) */
  for (rr=w03+0, cs=(&w04); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #31: @4 = @2[4] */
  for (rr=(&w04), cs=w02+4; cs!=w02+5; cs+=1) *rr++ = *cs;
  /* #32: @16 = (@4*@11) */
  w16  = (w04*w11);
  /* #33: @17 = (@14*@9) */
  w17  = (w14*w09);
  /* #34: @16 = (@16-@17) */
  w16 -= w17;
  /* #35: (@3[1] += @16) */
  for (rr=w03+1, cs=(&w16); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #36: @16 = (@15*@9) */
  w16  = (w15*w09);
  /* #37: @10 = (@4*@10) */
  w10  = (w04*w10);
  /* #38: @16 = (@16-@10) */
  w16 -= w10;
  /* #39: (@3[2] += @16) */
  for (rr=w03+2, cs=(&w16); rr!=w03+3; rr+=1) *rr += *cs++;
  /* #40: @1 = (@1*@3) */
  for (i=0, rr=w01, cs=w03; i<3; ++i) (*rr++) *= (*cs++);
  /* #41: (@0[4:7] += @1) */
  for (rr=w00+4, cs=w01; rr!=w00+7; rr+=1) *rr += *cs++;
  /* #42: @13 = (@13*@9) */
  w13 *= w09;
  /* #43: @12 = (@12*@11) */
  w12 *= w11;
  /* #44: @13 = (@13-@12) */
  w13 -= w12;
  /* #45: (@0[5] += @13) */
  for (rr=w00+5, cs=(&w13); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #46: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #47: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #48: @12 = 0 */
  w12 = 0.;
  /* #49: @11 = (-@4) */
  w11 = (- w04 );
  /* #50: @9 = (-@15) */
  w09 = (- w15 );
  /* #51: @16 = (-@14) */
  w16 = (- w14 );
  /* #52: @19 = horzcat(@12, @11, @9, @16) */
  rr=w19;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w16;
  /* #53: @19 = @19' */
  /* #54: @20 = horzcat(@4, @12, @14, @9) */
  rr=w20;
  *rr++ = w04;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w09;
  /* #55: @20 = @20' */
  /* #56: @21 = horzcat(@15, @16, @12, @4) */
  rr=w21;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  *rr++ = w04;
  /* #57: @21 = @21' */
  /* #58: @22 = horzcat(@14, @15, @11, @12) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w12;
  /* #59: @22 = @22' */
  /* #60: @23 = horzcat(@19, @20, @21, @22) */
  rr=w23;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  /* #61: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #62: @24 = (@13*@24) */
  for (i=0, rr=w24, cs=w24; i<16; ++i) (*rr++)  = (w13*(*cs++));
  /* #63: @23 = @24' */
  for (i=0, rr=w23, cs=w24; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #64: @18 = mac(@23,@7,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w23+j, ct=w07+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #65: (@0[:4] += @18) */
  for (rr=w00+0, cs=w18; rr!=w00+4; rr+=1) *rr += *cs++;
  /* #66: @23 = zeros(4x4) */
  casadi_clear(w23, 16);
  /* #67: @18 = @2[:4] */
  for (rr=w18, cs=w02+0; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #68: @18 = @18' */
  /* #69: @23 = mac(@7,@18,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w07+j, ct=w18+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #70: @23 = (@13*@23) */
  for (i=0, rr=w23, cs=w23; i<16; ++i) (*rr++)  = (w13*(*cs++));
  /* #71: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #72: {@7, @18, @19, @20} = horzsplit(@24) */
  casadi_copy(w24, 4, w07);
  casadi_copy(w24+4, 4, w18);
  casadi_copy(w24+8, 4, w19);
  casadi_copy(w24+12, 4, w20);
  /* #73: @20 = @20' */
  /* #74: {@13, @14, @15, NULL} = horzsplit(@20) */
  w13 = w20[0];
  w14 = w20[1];
  w15 = w20[2];
  /* #75: @19 = @19' */
  /* #76: {@11, @12, NULL, @16} = horzsplit(@19) */
  w11 = w19[0];
  w12 = w19[1];
  w16 = w19[3];
  /* #77: @13 = (@13-@12) */
  w13 -= w12;
  /* #78: @18 = @18' */
  /* #79: {@12, NULL, @4, @9} = horzsplit(@18) */
  w12 = w18[0];
  w04 = w18[2];
  w09 = w18[3];
  /* #80: @13 = (@13+@4) */
  w13 += w04;
  /* #81: @7 = @7' */
  /* #82: {NULL, @4, @10, @17} = horzsplit(@7) */
  w04 = w07[1];
  w10 = w07[2];
  w17 = w07[3];
  /* #83: @13 = (@13-@17) */
  w13 -= w17;
  /* #84: (@0[6] += @13) */
  for (rr=w00+6, cs=(&w13); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #85: @14 = (@14+@11) */
  w14 += w11;
  /* #86: @14 = (@14-@9) */
  w14 -= w09;
  /* #87: @14 = (@14-@10) */
  w14 -= w10;
  /* #88: (@0[5] += @14) */
  for (rr=w00+5, cs=(&w14); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #89: @16 = (@16-@15) */
  w16 -= w15;
  /* #90: @16 = (@16+@12) */
  w16 += w12;
  /* #91: @16 = (@16-@4) */
  w16 -= w04;
  /* #92: (@0[4] += @16) */
  for (rr=w00+4, cs=(&w16); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #93: output[0][0] = @0 */
  casadi_copy(w00, 7, res[0]);
  /* #94: output[0][1] = @5 */
  if (res[0]) casadi_copy(w05, 3, res[0]+7);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_rot_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 103;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 103*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
