/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_rot_mpc_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {10, 1, 1};
static const casadi_int casadi_s6[23] = 
  {10, 10, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 3, 4, 5,
  6, 7, 8, 9, 0, 1, 2};
static const casadi_int casadi_s7[3] = {10, 0, 1};

/* quad_rot_mpc_cost_y_fun_jac_ut_xt:(i0[7],i1[3],i2[0],i3[],i4[4])->(o0[10],o1[10x10,10nz],o2[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w0, *w1=w+1, *w2=w+8, *w3=w+12, w4, *w5=w+17, w6, *w7=w+21, *w8=w+31, *w9=w+41;
  const casadi_real *cs;
  /* #0: @0 = 10 */
  w0 = 10.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 7, w1);
  /* #2: @2 = @1[:4] */
  for (rr=w2, cs=w1+0; cs!=w1+4; cs+=1) *rr++ = *cs;
  /* #3: @3 = input[4][0] */
  casadi_copy(arg[4], 4, w3);
  /* #4: @2 = (@2-@3) */
  for (i=0, rr=w2, cs=w3; i<4; ++i) (*rr++) -= (*cs++);
  /* #5: @2 = (@0*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #6: output[0][0] = @2 */
  casadi_copy(w2, 4, res[0]);
  /* #7: @4 = 5 */
  w4 = 5.;
  /* #8: @5 = @1[4:7] */
  for (rr=w5, cs=w1+4; cs!=w1+7; cs+=1) *rr++ = *cs;
  /* #9: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #10: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #11: @6 = 0.01 */
  w6 = 1.0000000000000000e-02;
  /* #12: @5 = input[1][0] */
  casadi_copy(arg[1], 3, w5);
  /* #13: @5 = (@6*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #14: output[0][2] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+7);
  /* #15: @7 = zeros(10x10,10nz) */
  casadi_clear(w7, 10);
  /* #16: @8 = ones(10x1) */
  casadi_fill(w8, 10, 1.);
  /* #17: {@5, @1} = vertsplit(@8) */
  casadi_copy(w8, 3, w5);
  casadi_copy(w8+3, 7, w1);
  /* #18: @2 = @1[:4] */
  for (rr=w2, cs=w1+0; cs!=w1+4; cs+=1) *rr++ = *cs;
  /* #19: @2 = (@0*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #20: @9 = @1[4:7] */
  for (rr=w9, cs=w1+4; cs!=w1+7; cs+=1) *rr++ = *cs;
  /* #21: @9 = (@4*@9) */
  for (i=0, rr=w9, cs=w9; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #22: @5 = (@6*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #23: @8 = vertcat(@2, @9, @5) */
  rr=w8;
  for (i=0, cs=w2; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #24: (@7[:10] = @8) */
  for (rr=w7+0, cs=w8; rr!=w7+10; rr+=1) *rr = *cs++;
  /* #25: output[1][0] = @7 */
  casadi_copy(w7, 10, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_rot_mpc_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quad_rot_mpc_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quad_rot_mpc_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_rot_mpc_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_rot_mpc_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 44;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_rot_mpc_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 44*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
